version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - needs triage
    groups:
      app-npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - needs triage
    groups:
      desktop-npm:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - needs triage
    groups:
      desktop-cargo:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: Europe/London
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - needs triage
    groups:
      github-actions:
        patterns:
          - "*"
